version: '3'
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/app
    working_dir: /var/www/app
    ports:
      - "3331:3000"
      - "3332:3001"
    command: sh -c "yarn dev"
    networks:
      - my-nsfnet
networks:
  my-nsfnet:
    name: my-nsfnet
    driver: bridge
