[build]
	command = "npm run build && npm run generate"
  functions = "functions"
	publish = "dist"
	node_bundler = "esbuild"

[dev]
	command = "npm run dev"
	functions = "functions"
	port = 3001
	targetPort = 3000
	publish = "dist"
	node_bundler = "esbuild"

