[build]
  functions = "functions"
	command = "yarn build && yarn generate"
	publish = "dist"
	
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301