[build]
	command = "yarn generate"
  functions = "functions"
	publish = "dist"

[dev]
	command = "yarn dev"
	functions = "functions"
	port = 3001
	targetPort = 3000
	publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/testing/*"
  to = "/.netlify/functions/:splat"
  status = 200
	force = true
